name: Build canary
on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *' # Everyday, at 00:00 IST
  push:
    branches: [ "master" ]


jobs:

  build-nixos:
    name: Build NixOS Systems
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Starting build
        run: |
          nix flake update
          ./scripts/nix-ci/builder.py --cross-aarch64-linux --nixosConfigurations

  build-homes:
    name: Build standalone home-manager configurations
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Starting build
        run: |
          nix flake update
          ./scripts/nix-ci/builder.py --cross-aarch64-linux --homeConfigurations

  build-packages:
    name: Build packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Starting build
        run: |
          nix flake update
          ./scripts/nix-ci/builder.py --cross-aarch64-linux --packages

  build-devshells:
    name: Build devshells
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Starting build
        run: |
          nix flake update
          ./scripts/nix-ci/builder.py --cross-aarch64-linux --devShells

  build-isos:
    name: Build NixOS ISOs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Starting build
        run: |
          nix flake update
          ./scripts/nix-ci/builder.py --cross-aarch64-linux --isoImages
