name: Continuous Build
run-name: Continuous Build (${{ github.repository }})

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '30 18 * * *' # Everyday, at 00:00 IST

env:
  NIXPKGS_RISCV_GHC_BOOTSTRAP_ISSUE: https://github.com/nixos/nixpkgs/issues/231537
  UPDATE_LOCKFILE: 1
  nix-build-cmd: nix build --print-build-logs --show-trace --max-jobs 1 --cores 0

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        linux_arches: [ aarch64, riscv64, x86_64 ]

    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "extra-platforms = aarch64-linux riscv64-linux x86_64-linux"
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: taiki-e/install-action@just

      - name: Setting up QEMU
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y binfmt-support qemu-user-static

      - name: Building NixOS ISO for ${{ matrix.linux_arches }}
        run: |
          if [[ '${{ matrix.linux_arches }}' != 'riscv64' ]]; then
              just actual-arch=${{ matrix.linux_arches }} build-iso
          else
              echo "RISC-V job for ${{ github.job }} skipped until $NIXPKGS_RISCV_GHC_BOOTSTRAP_ISSUE is resolved."
          fi

  build-nixos-system:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        machines: [ flameboi, sentinel, reddish, mahadev, pawandev, stuti, vaaman, vaayu ]

    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "extra-platforms = aarch64-linux riscv64-linux x86_64-linux"
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: taiki-e/install-action@just

      - name: Setting up QEMU
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y binfmt-support qemu-user-static

      - name: Building NixOS configuration for ${{ matrix.machines }}
        run: |
          if [[ "$(nix eval --raw .#nixosConfigurations.${{ matrix.machines }}.pkgs.stdenv.system)" != 'riscv64-linux' ]]; then
              just actual-arch=emulated nixos-machine-hostname=${{ matrix.machines }} build-nixos-system
          else
              echo "RISC-V job for ${{ github.job }} skipped until $NIXPKGS_RISCV_GHC_BOOTSTRAP_ISSUE is resolved."
          fi

  build-home-manager-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        linux_arches: [ aarch64, riscv64, x86_64 ]
        homeOf: [ pratham ]

    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "extra-platforms = aarch64-linux riscv64-linux x86_64-linux"
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: taiki-e/install-action@just

      - name: Setting up QEMU
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y binfmt-support qemu-user-static

      - name: Building home-manager configuration for ${{ matrix.homeOf }}
        run: |
          if [[ '${{ matrix.linux_arches }}' != 'riscv64' ]]; then
              just actual-arch=${{ matrix.linux_arches }} hm-user=${{ matrix.homeOf }} build-home-manager
          else
              echo "RISC-V job for ${{ github.job }} skipped until $NIXPKGS_RISCV_GHC_BOOTSTRAP_ISSUE is resolved."
          fi

  build-home-manager-darwin:
    runs-on: macos-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        homeOf: [ pratham ]

    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: taiki-e/install-action@just

      - name: Building home-manager configuration for ${{ matrix.homeOf }}
        run: |
          if [[ "$(uname -m)" == 'x86_64' ]]; then
              system_attr='x86_64-darwin'
          elif [[ "$(uname -m)" == 'arm64' ]]; then
              system_attr='aarch64-darwin'
          else
              echo "well well well, look what we have... Darwin on $(uname -m)"
              exit 1
          fi
          just hm-user=${{ matrix.homeOf }} build-home-manager
